# Generated by Django 3.2.9 on 2021-11-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentemail',
            name='email',
            field=models.EmailField(default='blank', max_length=254),
        ),
    ]
