# Generated by Django 3.2.9 on 2021-11-11 09:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_sentemail_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentemail',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
