# Generated by Django 3.2.7 on 2021-11-20 10:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0005_auto_20211120_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupstructure',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='group_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
