# Generated by Django 3.2.7 on 2021-11-20 10:52

import chat.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0006_alter_groupstructure_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupstructure',
            name='admins',
            field=models.ManyToManyField(default=chat.models.current_user, related_name='group_admins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groupstructure',
            name='members',
            field=models.ManyToManyField(default=chat.models.current_user, related_name='group_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
