# Generated by Django 3.2.7 on 2021-11-25 07:10

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20211122_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupstructure',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=chat.models.GroupAvatr),
        ),
    ]
